<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle()->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>
        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-xs-12 col-sm-12" id="top-navigation">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-8">
                                <ul class="unstyled list-inline">
                                    <li>06 Dec 2010</li>
                                    <li>06 Dec 2010</li>
                                    <li>06 Dec 2010</li>
                                    <li>06 Dec 2010</li>
                                </ul>
                            </div>
                            <div col-sm-4>
                                <div class="pull-right">
                                    <span>Subscribe by RSS or Emaiil for updates!</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 col-xs-12" id="header">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-12 col-xs-12">
                                
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            
            <div class="row">
                <div class="col-sm-12 col-xs-12" id="navigation">
                    <?php echo $this->navigation('navigation')->menu()->setUlClass('navigation-bar'); ?>
                </div>
            </div>
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
